### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jsolson** [Angel-125/WildBlueTools#5]
Using WBIResourceSwitcher I need a way to adjust the mass of the part based on the capacityFactor. Adding a property to the templates called massAdjust (whatever) and then setting the part mass to `template.mass + template.massAdjust * capacityFactor` would accomplish this. A similar feature for cost would also make sense.

Some minor requests: When not using the full GUI, a single UI_ChooseOption (I think that's what it's called) control would be cleaner than individual next/previous/current configuration controls. It's the thing that has left and right buttons, with the current selection in the middle.

The GetInfo call could certainly display the list of templates rather than check the tweakables menu.

**Comment by CobaltWolf** [comment]
Additional request, for balloon tanks - the ability to enable/disable surface attach of other parts. I understand that it would be hard to prevent people from surface attaching something, THEN switching to balloon tanks. But a minimum functionality to allow it would be very helpful. Otherwise we can probably just include some information in the description telling people not to...
